CREATE DATABASE NexCart_Analytics;
USE NexCart_Analytics;
show tables ;

-- ----ALTAR TABLES---------------
ALTER TABLE fact_order_items
MODIFY OrderItemID VARCHAR(20) NOT NULL,
MODIFY OrderID VARCHAR(20) NOT NULL,
MODIFY CustomerID VARCHAR(20) NOT NULL,
MODIFY ProductID VARCHAR(20) NOT NULL,
MODIFY SellerID VARCHAR(20) NOT NULL,
MODIFY WarehouseID VARCHAR(20) NOT NULL,
MODIFY DeliveryDateKey INT,

MODIFY PaymentMethod VARCHAR(30),
MODIFY OrderStatus VARCHAR(30),
MODIFY IsReturned VARCHAR(5),

MODIFY EventName VARCHAR(100),
MODIFY EventType VARCHAR(50);

ALTER TABLE fact_inventory_snapshot
MODIFY InventoryID VARCHAR(20) NOT NULL,
MODIFY WarehouseID VARCHAR(20) NOT NULL,
MODIFY ProductID VARCHAR(20) NOT NULL,
MODIFY StockStatus VARCHAR(30);

ALTER TABLE dim_customer
MODIFY CustomerID VARCHAR(20) NOT NULL,
MODIFY CustomerCode VARCHAR(20),
MODIFY FirstName VARCHAR(50),
MODIFY LastName VARCHAR(50),
MODIFY FullName VARCHAR(100),
MODIFY Gender VARCHAR(10),
MODIFY AgeGroup VARCHAR(30),
MODIFY Email VARCHAR(100),
MODIFY Phone VARCHAR(20),
MODIFY City VARCHAR(50),
MODIFY State VARCHAR(50),
MODIFY Region VARCHAR(30),
MODIFY CustomerSegment VARCHAR(30),
MODIFY PreferredCategory VARCHAR(50),
MODIFY IsPrimeMember VARCHAR(5),
MODIFY IsActive VARCHAR(5);

ALTER TABLE dim_date
MODIFY FullDate DATE,
MODIFY MonthName VARCHAR(20),
MODIFY Quarter VARCHAR(10),
MODIFY DayName VARCHAR(20),
MODIFY FinancialYear VARCHAR(20),
MODIFY Season VARCHAR(20),
MODIFY IsWeekend VARCHAR(5);

ALTER TABLE dim_product
MODIFY ProductID VARCHAR(20) NOT NULL,
MODIFY SKUCode VARCHAR(30),
MODIFY ProductName VARCHAR(150),
MODIFY SKUName VARCHAR(200),
MODIFY Category VARCHAR(50),
MODIFY SubCategory VARCHAR(50),
MODIFY Brand VARCHAR(50),
MODIFY Model VARCHAR(100),
MODIFY Variant VARCHAR(100),
MODIFY ProductLifecycle VARCHAR(30),
MODIFY LaunchDate DATE,
MODIFY IsActive VARCHAR(5);

ALTER TABLE dim_seller
MODIFY SellerID VARCHAR(20) NOT NULL,
MODIFY SellerCode VARCHAR(20),
MODIFY SellerName VARCHAR(150),
MODIFY SellerType VARCHAR(50),
MODIFY BusinessCategory VARCHAR(50),
MODIFY GSTNumber VARCHAR(30),
MODIFY PANNumber VARCHAR(20),
MODIFY City VARCHAR(50),
MODIFY State VARCHAR(50),
MODIFY Region VARCHAR(30),
MODIFY RegistrationDate DATE,
MODIFY FulfillmentType VARCHAR(30),
MODIFY IsVerified VARCHAR(5),
MODIFY IsActive VARCHAR(5);

ALTER TABLE dim_warehouse
MODIFY WarehouseID VARCHAR(20) NOT NULL,
MODIFY WarehouseCode VARCHAR(20),
MODIFY WarehouseName VARCHAR(100),
MODIFY WarehouseType VARCHAR(50),
MODIFY City VARCHAR(50),
MODIFY State VARCHAR(50),
MODIFY Region VARCHAR(30),
MODIFY ManagerName VARCHAR(100),
MODIFY ContactNumber VARCHAR(20),
MODIFY TemperatureControlled VARCHAR(5),
MODIFY OpeningDate DATE,
MODIFY IsActive VARCHAR(5);